### ISSUE TITLE
TypeError: float() argument must be a string or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by Rudy996** [cppmyk/stargate-bridger#5]
![image](https://github.com/cppmyk/layerzero-bridger/assets/50031661/1628fced-61f2-4b57-9186-cffc501c08c1)

TypeError: float() argument must be a string or a real number, not 'NoneType'

How do I fix it?

**Comment by cppmyk** [comment]
Check your .env file. It should have a line specifying the Stargate slippage parameter. 
Something like this:
`STARGATE_SLIPPAGE=0.01`

**Comment by Rudy996** [comment]
I'm sorry for my stupidity, I accidentally deleted a dot in the .env file
